# Generated by Django 4.2.3 on 2023-07-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_clothes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothes',
            new_name='Cloth',
        ),
    ]
